In [3]:
import pandas as pd

books = pd.read_parquet("../data/processed/works.parquet")
books

,title,title_source,subtitle,authors,authors_source,description,description_source,language,isbn13s,tags,...,sources,n_records,gr_popularity,gr_avg_rating,g7k_popularity,g7k_avg_rating,bx_popularity,bx_avg_rating,has_description,has_tags
work_id,,,,,,,,,,,,,,,,,,,,,
OL1000001W,Ghost Of A Chance,bookcrossing,NaN,[Bill Crider],bookcrossing,NaN,NaN,en,[9780373263967],"[Detective And Mystery Stories, Fiction, Gener...",...,[bookcrossing],1,0,NaN,0,NaN,4,NaN,False,True
OL1000005W,Murder most fowl,bookcrossing,NaN,[Bill Crider],bookcrossing,NaN,NaN,en,[9780312113872],"[Detective And Mystery Stories, Texas, Fiction...",...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,True
OL100000W,Bloody Kin,bookcrossing,NaN,[Margaret Maron],bookcrossing,NaN,NaN,en,[9780385232319],"[Detective And Mystery Stories, Fiction, Gener...",...,[bookcrossing],1,0,NaN,0,NaN,4,NaN,False,True
OL1000012W,Outrage at Blanco,bookcrossing,NaN,[Bill Crider],bookcrossing,NaN,NaN,en,[9780440234548],"[Fiction, Rape, General, Revenge]",...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,True
OL1000014W,A romantic way to die,bookcrossing,NaN,[Bill Crider],bookcrossing,NaN,NaN,en,"[9780312209070, 9780373264407]","[Detective And Mystery Stories, Romance, Texas...",...,[bookcrossing],2,0,NaN,0,NaN,4,9.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
unmapped_9997410440,Nine Hours to Rama,bookcrossing,NaN,[],NaN,NaN,NaN,NaN,[9789997410443],[],...,[bookcrossing],1,0,NaN,0,NaN,1,10.0,False,False
unmapped_9997550773,The Story of Ireland,bookcrossing,NaN,[],NaN,NaN,NaN,NaN,[9789997550774],[],...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,False
unmapped_9997555627,My Sweet Orange Tree,bookcrossing,NaN,[],NaN,NaN,NaN,NaN,[9789997555625],[],...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,False
unmapped_9998150752,Complete Guide to Effective English: Harbrace ...,bookcrossing,NaN,[],NaN,NaN,NaN,NaN,[9789998150751],[],...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,False
unmapped_9999991556,Impact of New Product Introductions on the Mar...,bookcrossing,NaN,[],NaN,NaN,NaN,NaN,[9789999991551],[],...,[bookcrossing],1,0,NaN,0,NaN,1,NaN,False,False

#### Remove books without description
- cannot be used for "Similar to LOTR" queries
- filters out also most books that are not in english and have None in language

In [4]:
books = books[books["description"].notna()]
books

,title,title_source,subtitle,authors,authors_source,description,description_source,language,isbn13s,tags,...,sources,n_records,gr_popularity,gr_avg_rating,g7k_popularity,g7k_avg_rating,bx_popularity,bx_avg_rating,has_description,has_tags
work_id,,,,,,,,,,,,,,,,,,,,,
OL100003W,Home fires,bookcrossing,NaN,[Margaret Maron],bookcrossing,North Carolina judge Deborah Knott investigate...,bookcrossing,en,[9780446608107],"[Arson, Detective And Mystery Stories, Mystery...",...,[bookcrossing],1,0,NaN,0,NaN,8,5.333333,True,True
OL1000053W,No Marriage of Convenience (Avon Romantic Trea...,bookcrossing,NaN,[Elizabeth Boyle],bookcrossing,"Mason St. Clair, the new Earl of Ashlin, has i...",bookcrossing,en,[9780380815340],"[Fiction, History, General, Romance]",...,[bookcrossing],1,0,NaN,0,NaN,8,10.000000,True,True
OL1000055W,Once Tempted,bookcrossing,NaN,[Elizabeth Boyle],bookcrossing,"Innocence LostA notorious rake, the Marquis of...",bookcrossing,en,[9780380815357],"[Spain, Romance, Fiction, General, Man-Woman R...",...,[bookcrossing],1,0,NaN,0,NaN,7,9.500000,True,True
OL1000062W,It takes a hero,bookcrossing,NaN,[Elizabeth Boyle],bookcrossing,Rebecca will have to take a page from her own ...,bookcrossing,en,[9780060549305],"[Romance, Fiction, General, History, Social Li...",...,[bookcrossing],1,0,NaN,0,NaN,3,6.500000,True,True
OL1000064W,One Night of Passion,bookcrossing,NaN,[Elizabeth Boyle],bookcrossing,They Met At London's Notorious Cyprian's Ball....,bookcrossing,en,[9780786249909],"[Romance, Fiction, General, History, Social Li...",...,[bookcrossing],1,0,NaN,0,NaN,16,7.666667,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
unmapped_0911662251,Kybalion: A Study of the Hermetic Philosophy o...,goodreads,NaN,"[Three Initiates, William Walker Atkinson]",goodreads,Entre os fragmentos de conhecimentos ocultos p...,goodreads,en,[9780911662252],"[Philosophy, Occult, Spirituality, Nonfiction,...",...,"[bookcrossing, goodreads]",2,7266,4.21,0,NaN,3,NaN,True,True
unmapped_155709103X,George Washington's Rules of Civility and Dece...,google7k,NaN,[George Washington],google7k,Copied out by hand as a young man aspiring to ...,google7k,NaN,[9781557091031],[History],...,"[bookcrossing, google7k]",2,0,NaN,758,4.10,1,8.000000,True,True
unmapped_1568821441,The Keeper's Companion,google7k,"Blasphemous Knowledge, Forbidden Secrets, and ...",[Keith Herber],google7k,"[CALL OF CTHULHU ROLEPLAYING] ""The Keeper's Co...",google7k,NaN,[9781568821443],[Games],...,"[bookcrossing, google7k]",2,0,NaN,63,3.97,1,10.000000,True,True
unmapped_1569716110,Domu: A Child's Dream,goodreads,NaN,[Katsuhiro Otomo],goodreads,"Old Cho, a disturbed old man with psychic powe...",goodreads,en,[9781569716113],"[Manga, Comics, Graphic Novels, Horror, Scienc...",...,"[bookcrossing, goodreads]",2,1672,4.12,0,NaN,1,7.000000,True,True
unmapped_188364254x,Little Novels of Sicily,goodreads,NaN,[Giovanni Verga],goodreads,"First Published in a single volume in 1883, th...",goodreads,en,[9781883642549],"[Short Stories, Classics, Italian Literature, ...",...,"[bookcrossing, goodreads]",2,191,3.76,0,NaN,1,NaN,True,True

In [8]:
import numpy as np

books["title_and_subtitle"] = (
    np.where(books["subtitle"].isna(), books["title"],
             books[["title", "subtitle"]].astype(str).agg(": ".join, axis=1))
)
books

TypeError: sequence item 1: expected str instance, float found